### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by Arch881010** [SX-9/socket-chat#1]
Unless I am being very stupid, running the js file (`node .`) and hosting the html file, doesn't work.
![image](https://github.com/SX-9/socket-chat/assets/111789310/2239897f-4065-4326-9d84-be31bd921613)
I recieve this in the console repeatedly.
![image](https://github.com/SX-9/socket-chat/assets/111789310/97b3fce6-e48c-421d-9901-141a200368e6)

**Comment by satr14washere** [comment]
so i forgot to delete that message the actual dashboard is at port 3000 in route /
